"""chnaged room number to small int

Revision ID: 0a8cbae593da
Revises: efe8f8597f84
Create Date: 2025-11-23 22:01:45.860848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0a8cbae593da'
down_revision: Union[str, Sequence[str], None] = 'efe8f8597f84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rooms', 'room_number',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.SmallInteger(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rooms', 'room_number',
               existing_type=sa.SmallInteger(),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)
    # ### end Alembic commands ###
