"""la till anatl gäster i booking

Revision ID: 4bfe71371157
Revises: e2df9de36a58
Create Date: 2025-12-11 08:44:53.178231

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4bfe71371157'
down_revision: Union[str, Sequence[str], None] = 'e2df9de36a58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('people', sa.SmallInteger(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookings', 'people')
    # ### end Alembic commands ###
