"""fixed soft delete

Revision ID: 4ea3f4249b9a
Revises: b3c1ac5cb2e2
Create Date: 2025-11-27 09:01:34.202201

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ea3f4249b9a'
down_revision: Union[str, Sequence[str], None] = 'b3c1ac5cb2e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
