"""add everything

Revision ID: 5982b4137611
Revises: 74d9539dfc78
Create Date: 2025-11-25 09:36:15.973062

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5982b4137611'
down_revision: Union[str, Sequence[str], None] = '74d9539dfc78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=False),
    sa.Column('last_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_guests')),
    sa.UniqueConstraint('email', name=op.f('uq_guests_email'))
    )
    op.create_table('rooms',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('room_number', sa.SmallInteger(), nullable=False),
    sa.Column('room_count', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rooms'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rooms')
    op.drop_table('guests')
    # ### end Alembic commands ###
