"""ändra nullable till true för bookingid

Revision ID: 6118a0fc87f1
Revises: 8161b0ae05ab
Create Date: 2025-12-01 13:17:56.999575

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6118a0fc87f1'
down_revision: Union[str, Sequence[str], None] = '8161b0ae05ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
