"""added timestamp mixin till guest

Revision ID: 7a900838cc6c
Revises: e8c48eaa5992
Create Date: 2025-11-27 08:43:52.800771

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a900838cc6c'
down_revision: Union[str, Sequence[str], None] = 'e8c48eaa5992'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guests', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('guests', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('guests', 'updated_at')
    op.drop_column('guests', 'created_at')
    # ### end Alembic commands ###
