"""tog bort many to many

Revision ID: 7e2dcb82a099
Revises: 22729eed036a
Create Date: 2025-11-27 10:35:52.846765

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '7e2dcb82a099'
down_revision: Union[str, Sequence[str], None] = '22729eed036a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_bookings_guest_ID_guests'), 'bookings', type_='foreignkey')
    op.drop_column('bookings', 'guest_ID')
    op.add_column('guests', sa.Column('booking_id', sa.Integer(), nullable=False))
    op.create_foreign_key(op.f('fk_guests_booking_id_bookings'), 'guests', 'bookings', ['booking_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_guests_booking_id_bookings'), 'guests', type_='foreignkey')
    op.drop_column('guests', 'booking_id')
    op.add_column('bookings', sa.Column('guest_ID', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('fk_bookings_guest_ID_guests'), 'bookings', 'guests', ['guest_ID'], ['id'])
    # ### end Alembic commands ###
