"""la till pris

Revision ID: 8161b0ae05ab
Revises: 2e16d6fbb6ed
Create Date: 2025-11-27 11:16:51.308068

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '8161b0ae05ab'
down_revision: Union[str, Sequence[str], None] = '2e16d6fbb6ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('paid', sa.Boolean(), nullable=False))
    op.add_column('invoices', sa.Column('price_per_night', sa.DECIMAL(precision=10, scale=2), nullable=False))
    op.add_column('invoices', sa.Column('expired', sa.Boolean(), nullable=False))
    op.alter_column('invoices', 'amount',
               existing_type=mysql.DECIMAL(precision=10, scale=0),
               type_=sa.DECIMAL(precision=10, scale=2),
               existing_nullable=False)
    op.add_column('rooms', sa.Column('price_per_night', sa.DECIMAL(precision=10, scale=2), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rooms', 'price_per_night')
    op.alter_column('invoices', 'amount',
               existing_type=sa.DECIMAL(precision=10, scale=2),
               type_=mysql.DECIMAL(precision=10, scale=0),
               existing_nullable=False)
    op.drop_column('invoices', 'expired')
    op.drop_column('invoices', 'price_per_night')
    op.drop_column('invoices', 'paid')
    # ### end Alembic commands ###
