"""ändra nullable till true för bookingid

Revision ID: 82edc1500b3e
Revises: 6118a0fc87f1
Create Date: 2025-12-01 13:20:42.944960

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '82edc1500b3e'
down_revision: Union[str, Sequence[str], None] = '6118a0fc87f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('guests', 'booking_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('guests', 'booking_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
