"""added connections in booking and booked date

Revision ID: 912c573c0319
Revises: 0d93516edfc5
Create Date: 2025-11-25 11:02:39.439389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '912c573c0319'
down_revision: Union[str, Sequence[str], None] = '0d93516edfc5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('guest_ID', sa.Integer(), nullable=False))
    op.add_column('bookings', sa.Column('room_ID', sa.Integer(), nullable=False))
    op.add_column('bookings', sa.Column('book_date', sa.DateTime(), nullable=False))
    op.add_column('bookings', sa.Column('booked_duration', sa.SmallInteger(), nullable=False))
    op.create_foreign_key(op.f('fk_bookings_room_ID_rooms'), 'bookings', 'rooms', ['room_ID'], ['id'])
    op.create_foreign_key(op.f('fk_bookings_guest_ID_guests'), 'bookings', 'guests', ['guest_ID'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_bookings_guest_ID_guests'), 'bookings', type_='foreignkey')
    op.drop_constraint(op.f('fk_bookings_room_ID_rooms'), 'bookings', type_='foreignkey')
    op.drop_column('bookings', 'booked_duration')
    op.drop_column('bookings', 'book_date')
    op.drop_column('bookings', 'room_ID')
    op.drop_column('bookings', 'guest_ID')
    # ### end Alembic commands ###
