"""switched connections on guest and booking

Revision ID: 9661d8aa98cc
Revises: cad833d4cee2
Create Date: 2025-12-05 20:14:35.677264

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '9661d8aa98cc'
down_revision: Union[str, Sequence[str], None] = 'cad833d4cee2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('guest_id', sa.Integer(), nullable=False))
    op.create_foreign_key(op.f('fk_bookings_guest_id_guests'), 'bookings', 'guests', ['guest_id'], ['id'])
    op.drop_constraint(op.f('fk_guests_booking_id_bookings'), 'guests', type_='foreignkey')
    op.drop_column('guests', 'booking_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guests', sa.Column('booking_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('fk_guests_booking_id_bookings'), 'guests', 'bookings', ['booking_id'], ['id'])
    op.drop_constraint(op.f('fk_bookings_guest_id_guests'), 'bookings', type_='foreignkey')
    op.drop_column('bookings', 'guest_id')
    # ### end Alembic commands ###
