"""added timestamp mixin till booked

Revision ID: b17259c0109b
Revises: 7a900838cc6c
Create Date: 2025-11-27 08:48:55.375679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b17259c0109b'
down_revision: Union[str, Sequence[str], None] = '7a900838cc6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('bookings', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookings', 'updated_at')
    op.drop_column('bookings', 'created_at')
    # ### end Alembic commands ###
