"""added soft delete to guests

Revision ID: b3c1ac5cb2e2
Revises: b17259c0109b
Create Date: 2025-11-27 08:58:54.946820

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3c1ac5cb2e2'
down_revision: Union[str, Sequence[str], None] = 'b17259c0109b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guests', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('guests', 'is_deleted')
    # ### end Alembic commands ###
