"""la till booking.id till invoice

Revision ID: e2df9de36a58
Revises: 9661d8aa98cc
Create Date: 2025-12-09 14:15:34.875112

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2df9de36a58'
down_revision: Union[str, Sequence[str], None] = '9661d8aa98cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('booking_id', sa.Integer(), nullable=False))
    op.create_foreign_key(op.f('fk_invoices_booking_id_bookings'), 'invoices', 'bookings', ['booking_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_invoices_booking_id_bookings'), 'invoices', type_='foreignkey')
    op.drop_column('invoices', 'booking_id')
    # ### end Alembic commands ###
