"""added booked to room as a boolean

Revision ID: e8c48eaa5992
Revises: 912c573c0319
Create Date: 2025-11-25 13:10:41.434028

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8c48eaa5992'
down_revision: Union[str, Sequence[str], None] = '912c573c0319'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('booked', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rooms', 'booked')
    # ### end Alembic commands ###
