"""added room count to rooms

Revision ID: efe8f8597f84
Revises: 84769db396f8
Create Date: 2025-11-23 22:00:45.551401

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efe8f8597f84'
down_revision: Union[str, Sequence[str], None] = '84769db396f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('email'), table_name='guests')
    op.create_unique_constraint(op.f('uq_guests_email'), 'guests', ['email'])
    op.add_column('rooms', sa.Column('room_count', sa.SmallInteger(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rooms', 'room_count')
    op.drop_constraint(op.f('uq_guests_email'), 'guests', type_='unique')
    op.create_index(op.f('email'), 'guests', ['email'], unique=True)
    # ### end Alembic commands ###
